<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="citrique3" nsURI="http://com.misc.projects.citrique3.emf" nsPrefix="ctr3">
  <eClassifiers xsi:type="ecore:EClass" name="CitriqueObject" eSuperTypes="../../com.misc.common.moplaf.propagator/model/propagator.ecore#//ObjectWithPropagatorFunctionAdapter">
    <eOperations name="refreshDescription"/>
    <eOperations name="refreshShortDescription"/>
    <eOperations name="refreshLongDescription"/>
    <eOperations name="refreshType"/>
    <eOperations name="refreshShortType"/>
    <eOperations name="refreshChildren"/>
    <eOperations name="init"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Child" upperBound="-1"
        eType="#//CitriqueObject" eOpposite="#//CitriqueObject/Parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parent" eType="#//CitriqueObject"
        eOpposite="#//CitriqueObject/Child"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ShortType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ShortDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LongDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ShortName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CitriqueDomain" eSuperTypes="#//CitriqueObject">
    <eOperations name="refresh"/>
    <eOperations name="activate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Plant" upperBound="-1"
        eType="#//Plant" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlantObject" eSuperTypes="#//CitriqueObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Plant" eType="#//Plant"
        eOpposite="#//Plant/PlantObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plant" eSuperTypes="#//CitriqueObject">
    <eOperations name="refreshNodes"/>
    <eOperations name="refreshLinks"/>
    <eOperations name="refreshObjects"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Buffer" upperBound="-1"
        eType="#//Buffer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Silo" upperBound="-1" eType="#//Silo"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="BufferSiloLink"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Reactor" upperBound="-1"
        eType="#//Reactor" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="BufferSiloLink"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Node" upperBound="-1" eType="#//PlantNode">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="BufferSiloLink"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Link" upperBound="-1" eType="#//PlantLink">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="BufferSiloLink"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BufferSiloLink" upperBound="-1"
        eType="#//BufferSiloLink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SiloReactorLink" upperBound="-1"
        eType="#//SiloReactorLink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PlantObject" upperBound="-1"
        eType="#//PlantObject" eOpposite="#//PlantObject/Plant"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Buffer" eSuperTypes="#//PlantNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SiloLinks" upperBound="-1"
        eType="#//BufferSiloLink" eOpposite="#//BufferSiloLink/Buffer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Silo" eSuperTypes="#//PlantNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="BufferLinks" upperBound="-1"
        eType="#//BufferSiloLink" eOpposite="#//BufferSiloLink/Silo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ReactorLinks" upperBound="-1"
        eType="#//SiloReactorLink" eOpposite="#//SiloReactorLink/Silo"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reactor" eSuperTypes="#//PlantNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SiloLinks" upperBound="-1"
        eType="#//SiloReactorLink" eOpposite="#//SiloReactorLink/Reactor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlantNode" eSuperTypes="#//PlantObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="PlantLink" eSuperTypes="#//PlantObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HeightFrom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HeightTo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BufferSiloLink" eSuperTypes="#//PlantLink">
    <eOperations name="refreshDispose">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="RefreshDispose calculate if the object must be dropped and drop it if so"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Silo" lowerBound="1" eType="#//Silo"
        eOpposite="#//Silo/BufferLinks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Buffer" lowerBound="1"
        eType="#//Buffer" eOpposite="#//Buffer/SiloLinks"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SiloReactorLink" eSuperTypes="#//PlantLink">
    <eOperations name="refreshDispose"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Silo" lowerBound="1" eType="#//Silo"
        eOpposite="#//Silo/ReactorLinks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Reactor" lowerBound="1"
        eType="#//Reactor" eOpposite="#//Reactor/SiloLinks"/>
  </eClassifiers>
</ecore:EPackage>
